#-----------------------------------------------------------------------

APP       := DemoApp
TARGET    := DemoServer
CONFIG    :=
STRIP_FLAG:= N
TARS2CPP_FLAG:=

INCLUDE   +=
LIB       += -lssl -lcrypto -lnghttp2

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------